### ISSUE TITLE
Sitemap made in server public_html directory, not blog directory

### ISSUE THREAD

**Issue by danielsale** [xenocrat/chyrp-lite#105]
I have my Chyrp Lite install in /blog and the sitemap is made in public_html. Is this a feature or a bug? I'd like it to be in public_html/blog if possible.

**Comment by xenocrat** [comment]
Hello there.

The sitemap is intentionally created in the document root. This is because you might have configured Chyrp with a canonical URL, for example installing your blog in _example.com/blog/_ but using _example.com_ as your canonical URL. In this case a search engine doesn’t know to look for _example.com/blog/sitemap.xml_, but it will always look for _example.com/sitemap.xml_ regardless of the document path.

This was an easy solution to the problem but clearly it’s not always the correct thing to do. I will add a settings option to specify the sitemap.xml location.

**Comment by danielsale** [comment]
Thanks. The only reason I inquired about this is in Google Webmaster Tools, if I input my site as /blog, it only allows the sitemap file to be added after that. The rest of my site contains apps like an RSS reader, Wallabag, etc., so I'm not interested in having them crawled.
