### ISSUE TITLE
Adapter drop-down box is blank

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#108]
@xenocrat Trying to install for a new project. The dropdown for Adapter is blank though. Naturally, if I try to continue, it will error with adapter not selected. Downloaded most recent github version as of today May 6, 2020. Any ideas?

**Comment by xenocrat** [comment]
Hello there.

The PDO database class is a modular system, requiring drivers for different types of databases. It appears your PHP installation has the PDO database class enabled, but no actual database drivers available. You need to get the PDO drivers for MySQL or SQLite added to your PHP installation, depending on which type of database you intend to use - documentation is [here](https://www.php.net/manual/en/pdo.installation.php).

Chyrp Lite checks for the availability of the MySQLi or PDO database classes before displaying the installer, but I don’t check for driver availability at this point. I’ll add that because it is clearly confusing to be greeted with an empty selector.

**Comment by kreativmind** [comment]
Thanks. Forgot to make sure it was enabled in php.ini file. Working now.
