### ISSUE TITLE
How to implementing recaptcha on login / register?

### ISSUE THREAD

**Issue by achmatch** [xenocrat/chyrp-lite#116]
Any ideas?

**Comment by xenocrat** [comment]
Hello there.

Take a look at the bundled [Maptcha module](https://github.com/xenocrat/chyrp-lite/tree/master/modules/maptcha) for an example of implementing a captcha. Chyrp Lite provides all the necessary hooks but you would have to implement the module yourself if you want to use Google's Recaptcha service.

**Comment by thethinkingman** [comment]
achmatch - I am happy to create a reCAPTURE v2 module for you. It will only work on the registration page though - like Maptcha does. I am new to Chyrp-Lite but not to PHP. I have already created a module (for my own use ATM) so it shouldn't be hard to do this one.

**Comment by achmatch** [comment]
Good news, then make it public repo.

**Comment by thethinkingman** [comment]
Yep. I have nearly finished it. I am just testing it out.. it's 2am here .. so bedtime. I won't work on it tomorrow as I am busy but it should be done the day after that.

**Comment by thethinkingman** [comment]
Here you go. Version 1.0 of the module.

http://thethinkingman.com.au/2020/10/07/recaptcha-v2-module-for-chyrp-lite/

_Admins:_ Please note that I will create a new thread to ask for information... mostly around the locales. Everything else was nice and easy -- thanks to the Likes module (good reference).

Obviously, you will need to register with Google and get a Site and Secret key. I have put some info into a Readme.txt file.

I have also added a debug option that allows you to check the response from Google. Enabling this prevents the user from being Registered... as I just kill the script. I'm sure that there is a nicer way of doing it... but I'll add that to v1.1.

Let me know how you go.

As Google javascript file runs using 'async defer' I couldn't use Chyrp-Lites scripts array.. so the <script> is located in the form.. just under the recaptcha div.

I have also had to include a stylesheet with the module as the theme that I was using (and which I expect is common) has a style for an iframe which made the recaptcha box look ugly.

You can modify the CSS if need be to suite your website.

My site looks plain right now as I haven't made up my own theme -- I'll work on that tomorrow.

**Comment by thethinkingman** [comment]
BTW: I have just updated the module to version 1.2.
Added:
- check to ensure that the PHP Curl extension is loaded (just in case)
- added a Version to the Settings page
- Moved the Readme into the Settings page
- Updated the Locale en_US file and created de_DE, it_IT and zn_CN
- Added better error messaging

Coolio.

**Comment by achmatch** [comment]
Thanks bro,

Btw, i try install your modules and i got error
`Error
syntax error, unexpected 'return' (T_RETURN)`

**Comment by thethinkingman** [comment]
All good. Download it again. I missed out a semi-colon. I edited it locally and in a rush.. didn't test. Sorry.

**Comment by thethinkingman** [comment]
Ok.... I tried it on another browser and noticed that the iframe was given a height (by ALL.css) so -- for the moment -- I have changed recaptchas iframe height to 78px; It should work for now but it might need a tweak.
It is now v1.22

**Comment by thethinkingman** [comment]
Heh. Ok.. I have changed it again... well the style .. as I don't like setting a static height. So... I have now made the height reset to its Initial iframe value.

The reason for my concern is that because sometimes the recaptcha will display the image block. If I had set the iframe to 78px then there is the possibility that a user will get the image block.

Anyway... it's upto 1.23. Small change... but needed.

**Comment by achmatch** [comment]
The Problem is, maptcha or recaptcha only appear in register page not login page.

**Comment by thethinkingman** [comment]
Login pages don't normally include a captcha... the system normally has intruder detection. ie. if someone tries to login from the same address X amount of times in X amount of minutes then it will lock them out for X amount of time.
Captcha is mainly used to ensure that what is registering to your website is a real person and not robot.
Normally registering is easier than guessing (or using a dictionary) to hack into an account.

I'm not saying you cannot achieve having it on the login page... because you can.... BUT ... as it is not the standard use of captcha I wouldn't see it making its way into the build...even as an option.

Here's how to achieve it:

1. Edit includes/controller/Main.php
Insert the following code at line: 582
                if (!check_captcha())
                    Flash::warning(__("Incorrect captcha response."));
2. Save and exit the file
3. Edit themes/<theme name>/forms/user/login.twig
4. Insert a new line and paste:
{{ generate_captcha() }}
Note: Add it before: {{ trigger.call("user_login") }}
5. Save and exit that file
All Done.
Test it out.

**Comment by achmatch** [comment]
Ok, done.
