### ISSUE TITLE
Support Forum

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#12]
@xenocrat Do you think it's possible we can talk about putting up a support forum? I would like to see more active users and give support as well as have a Showcase topic to display existing sites. I think it will help gain recognition and build a follower base.

Thoughts?

**Comment by xenocrat** [comment]
As a hobbyist solo developer, sadly I don't have the time to dedicate to maintaining and moderating a forum. Chyrp Lite's following is also tiny right now. If I created a dedicated forum I think it would be a very lonely place, populated mostly by spambots.

At the end, the old Chyrp forums were overwhelmed by spam issues and registration had to be disabled. This is why I've chosen to use GitHub's wiki and issue tracker for Chyrp Lite – offload the administration of the community platform to professionals, so I can spend my precious spare time butchering code. ;-)

Imho Chyrp's single biggest community engagement failure was the lack of visible and well-maintained documentation; this is essential for a platform that isn't so popular that users and developers can simply go to Google for quick answers. I've tried to make the wiki here a newbie-friendly and helpful resource, so hopefully that issue has been addressed.

I'm always willing to handle support questions as well as bug reports using GitHub's issue tracker, and to be brutally honest I think the quality of feedback I receive here from the GitHub community is much better than I would get anywhere else.

Now that Chyrp Lite has a proper [homepage](http://chyrplite.net) it is appearing a bit more prominently in search engine results, which I think is the first and most important step in project visibility. The lack of a showcase is a shame, but I think right now that's not an urgent problem given the tiny user base. In future it could be addressed with a showcase wiki page.

I know it seems that I am replying "no, no, and no" but I tread cautiously because I only want to build something I can also support in future. There's a few voices around the web these days extolling the virtues of self-hosting and not ceding control of the open web to corporations. I think Chyrp Lite could be a great tool for that purpose and perhaps it will rise in popularity if this sentiment catches on, but I don't plan for nor expect this to happen. I don't consider Chyrp Lite to be a platform or a brand, but simply a good tool suitable for a job worth doing.

Sorry for the long post. I should probably get a blog. ;-p

**Comment by kreativmind** [comment]
I saw where Chyrp has had some activity about a new facelift Arian had on his old drive from a year ago. Someone was mentioning about hosting the Chyrp site to keep it going. I chimed in and asked some questions but yet to receive a reply from him. Have you followed the repo for Chyrp?

**Comment by xenocrat** [comment]
I check in on the repo every now and then to see if there are new commits or signs of activity. It's looking dead to me, but I'd be happy to be proved wrong.

**Comment by kreativmind** [comment]
@xenocrat Take a look
https://github.com/chyrp/chyrp/issues/174#issuecomment-176512670

**Comment by xenocrat** [comment]
Thanks for the link.
