### ISSUE TITLE
Misc Questions

### ISSUE THREAD

**Issue by thethinkingman** [xenocrat/chyrp-lite#125]
Hey,

A few questions:
1) I have noticed that Chyrp-Lite supports 4 languages (en_US, de_DE, it_IT and zh_CN) but most of the modules are missing German. If the system supports 4 languages shouldn't the modules support the 4 langauges? (I am only asking as I have been doing the locale for all 4).

2) There are many modules included and feathers but there is no information about them... especially about what they do and how to use them. I can make assumptions and play but it would be nice if the Wiki (or whatever) contains information about them.

3) Is there a site for general/technical questions -- I feel bad asking on here -- it doesn't seem appropriate (in an issues area)

4) I am working on a new module (editorMD JS Markdown Editor module). Is there somewhere that I can put it and tell  people about it or do I just put it on my site. I know that there are not a lot of themes, modules etc for Chyrp-Lite (yet) but I was just wondering.

5) I would like to help out. I could create the other language files. I could create some extra themes. Etc Etc. Obviously I am green when it comes to Chyrp-Lite but I get up to speed very quickly and would like to offer my assistance. Something to think about.

6) What program (if any) do you use to edit the POT files. I am wondering if I should fork out the cash to buy the pot editor I found before or just keep doing things manually. Which I don't mind as it isn't often.

Thanks

**Comment by xenocrat** [comment]
Hello again. A few answers:

1. The German translation was kindly donated by a user, but modules were not translated. I'd be very happy if some day another German speaker is inspired to make the rest. The absence of some translation domains is not a problem, but clearly it affects the usefulness of the German translation.
2. The [wiki](https://github.com/xenocrat/chyrp-lite/wiki) slowly expands. Feedback noted.
3. It's fine to ask here. I don't have the time or resources to go elsewhere, and there is not a large community around Chyrp Lite.
4. Create an issue. I will label it appropriately and perhaps pin it. I know this is bending the purpose of issues quite a bit, but it's low friction and it gets the job done.
5. Good translations by native speakers are extremely welcome. I would love to expand Chyrp Lite's language support. Themes are less likely to be incorporated because I want to keep the install size of Chyrp Lite to a minimum and not overwhelm myself with future maintenance tasks, but I will certainly promote any theme that is mentioned. If there are enough extensions to mention, I will add a section to the wiki homepage with links to the repos.
6. [POEdit](https://poedit.net/) is great and free.

**Comment by thethinkingman** [comment]
POEdit was what I had downloaded - I'll give it another go.
I have a few technical questions that I will put in another issue. (I also have to remember what they were).
Thanks again for the prompt response.
