### ISSUE TITLE
Markdown editor

### ISSUE THREAD

**Issue by dahliadahlia** [xenocrat/chyrp-lite#13]
Any chance a markdown editor will be introduced in the core or as an extension?

I know the original Chyrp had an extension for it, though I can't remember the name.

**Comment by xenocrat** [comment]
Chyrp Lite includes built-in Markdown support. So long as you have the feature enabled (you can find it in the Content settings tab), you can write Markdown into most content fields and get a quick preview of the rendered result by clicking on the magnifying glass icon above the field. Click on the "M" icon for a cheat sheet.

Chyrp 2.6 included the [Redactor](https://imperavi.com/redactor) WYSIWYG editor thanks to the kind support of a sponsor who paid for the cost of licensing. Chyrp Lite does not have a [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) editor and there are no plans to add one, but this could be achieved by someone writing a module.

Redactor does not support Markdown; its creates HTML markup. I investigated a few options for Chyrp Lite, but in the end I decided against including a WYSIWYG editor because ultimately the markup they produce is nasty stuff.

**Comment by dahliadahlia** [comment]
Thanks for the quick feedback. I'm sad to read that there will be no WYSIWYG editor but I understand your reasoning.

I'll try my hand at adding it to my own install but I'm by no means a programmer.

**Comment by xenocrat** [comment]
Interesting link, I will take a closer look at that one.

**Comment by kreativmind** [comment]
Looks promising and pretty cool

**Comment by xenocrat** [comment]
SimpleMDE is under consideration as a bundled module for a future release.
