### ISSUE TITLE
Inline images

### ISSUE THREAD

**Issue by pwac092** [xenocrat/chyrp-lite#133]
Hiya! 

First of all, let me tell you, this is a great project.

I had this very complicated system to keep an online log and this has completely taken over. 

Just a quick question, is there a way to include inline images in an entry?

**Comment by michaelwylde** [comment]
The posts support markdown so you can add an inline image using the markdown syntax.
A markdown cheatsheet can be foud here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

With the specific image markdown being:
`![<alt_text>](<image_url> "<image_title>")`

**Comment by pwac092** [comment]
Thank you for your reply Michael!

No yeah that I get, but that would require me to scp the file to the server where this is hosted and I was wondering whether there was a way to insert an image while typing the post.

**Comment by xenocrat** [comment]
Hello there. Thank you for the kind words about Chyrp Lite!

The answer to your question is yes, kind of. Be warned, this is not a streamlined process.

1. Go to the Manage > Import page and bulk upload one or more files.
2. Go to the Manage > Export page and click on the ? help icon alongside Uploads Manifest.
3. Find the file you uploaded in the list and copy the link location.
4. Paste this into your blog post inside an image tag (Markdown or HTML).

All the requirements are in place for a module that offers file uploads on-page when writing posts. Designing a desktop- and mobile-friendly UI for this kind of module is a pain that I don't want to take on, but I might do a bare bones version because it would be beneficial for some users.

**Comment by xenocrat** [comment]
I've implemented drag-and-drop image upload on the write pages. Won't work on mobile, but it gets the job done for desktop users. This will be included in the next release.
