### ISSUE TITLE
How to show list of pages?

### ISSUE THREAD

**Issue by epsilon-0** [xenocrat/chyrp-lite#134]
So I have a series of posts as well as some independent pages, like an About Me page. These are not blog posts.
Is there a way to show these pages in a menu bar?

Thanks!

**Comment by xenocrat** [comment]
Hello there.

If you use the Blossom or Topaz themes, your [pages](https://github.com/xenocrat/chyrp-lite/wiki/Glossary-of-Terms#page) will be listed in the sidebar (see [here](https://github.com/xenocrat/chyrp-lite/wiki/Theme-Gallery)). If you use Sparrow or Umbra themes, you must modify the blog templates yourself because those themes are tumbleblog-style and don't surface pages, although they do support them.

**Comment by epsilon-0** [comment]
Yes, I am using the umbra theme, because it's a nice dark theme.
I suppose I'll use the topaz theme instead, it's nice too :smiley_cat:
