### ISSUE TITLE
How to increase iframe sizes (height)?

### ISSUE THREAD

**Issue by carforge** [xenocrat/chyrp-lite#136]
Hi all.

I try to embed a video by using the iframe HTML code provided by another website.
I already noticed that iframes have always small heights. Is there a way to increase the iframe-size to 100% of the content to be displayed? In my case the Video-iframe has a height of 281px.

Already tried to modify the ALL.css - without success.

```
/* Group: iFrames */

.iframe_background {
    display: block;
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0px;
    left: 0px;
    /* Prevent other elements overlapping */
    z-index: 1;
    background-color: rgba(239, 239, 239, 0.75);
}
.iframe_foreground {
    box-sizing: border-box;    
    display: block;
    position: absolute;
    margin: 0em;
    top: calc(0% + 48px);
    left: calc(25% - 48px);
    width: calc(50% + 96px);
    height: calc(50% + 96px);
    overflow-x: hidden;
    overflow-y: auto;
    border: none;
    background-color: #ffffff;
    box-shadow: 0px 4px 16px 2px rgba(79, 79, 79, 0.5);
}
.iframe_close_gadget {
    display: block;
    position: absolute;
    width: 24px;
    height: 24px;
    top: 24px;
    right: calc(25% - 72px);
    cursor: pointer;
}
.iframe_close_gadget img {
    width: 24px;
    height: 24px;
}
```

**Comment by carforge** [comment]
ADDITION: I try to embed a video **IN A BLOG POST** by using the iframe HTML code provided by another website.

**Comment by xenocrat** [comment]
Hello there.

The snippet you quoted is from the admin console’s stylesheet and does not affect display of blog posts - for that you would edit the rules of all.css in the folder of whatever theme you are currently using, e.g. _themes/blossom/stylesheets/all.css_.

I’ve set iframes to maintain 16:9 ratio in blog posts because this works for video, which is by far the most common type of embed. If you want to override this, you can add a style rule to the iframe when you embed it. For example:

    <iframe style="height: 281px;">

You need to know the height of the embedded content in advance if you want to set the iframe to 100% of that height.

**Comment by carforge** [comment]
1st: You're right, sorry! Needed to edit the ALL.css of the Theme.

2nd: The Embed-Code was:
```<iframe width='500' height='281' src='https://home.kind.of.vid.eo'></iframe>```

It worked when I use your solution:
```<iframe style="height: 281px; width: 500px;" src='https://home.kind.of.vid.eo'></iframe>```

Thanks a lot!
