### ISSUE TITLE
Error after Upgrade

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#14]
Twig Error
Unknown "items" filter in "layouts/default.twig" at line 20.
Backtrace

    includes/controller/Main.php on line 773
    modules/homepage/homepage.php on line 36
    includes/class/Trigger.php on line 83
    includes/class/Trigger.php on line 59
    includes/class/Route.php on line 117
    includes/class/Route.php on line 117

**Comment by kreativmind** [comment]
The homepage module is triggering the first few errors. Then I had to change the theme back to Sparrow. The really bad thing...is my homepage was replaced by My Awesome Homepage instead of all the css and markdown I wrote.

Not a good thing...at all.

**Comment by xenocrat** [comment]
You don't need the module any more, the feature has been built-in since Kordofan (Settings > Routes > Homepage). I've just tested it on my dev box and everything looks ok. You should be able to toggle the feature without overwriting or deleting any existing page at _/home_.

Could be the error is caused by the built-in feature and the module colliding, or the outdated module might have an incompatibility with Socotra. Which theme were you using when you got the error in _layouts/default.twig_?

**Comment by kreativmind** [comment]
Using Sparrow. When disabling homepage module it removed page content from the database. I restored the dB to get my content back.

**Comment by xenocrat** [comment]
_Unknown "items" filter_ refers to a Twig filter that has been removed in the latest version of Sparrow (it's no longer needed thanks to the Twig 1.23 upgrade). Only reason you would see that message is if you didn't upgrade Sparrow at the same time as you did your Socotra upgrade. If you did upgrade Sparrow along with your Socotra upgrade, the error might be caused by an old cache file.

Homepage module should have prompted you with the question "Do you want to delete the homepage?" when you disabled it. If you click OK then your page is deleted. The built-in version of the homepage feature is safer because it doesn't do deletions under any circumstances.

**Comment by kreativmind** [comment]
Unfortunately I didn't receive a prompt. In regards to the sparrow update, I updated from the latest version of chyrp to the latest release. I am not sure which version of sparrow I had installed.
