### ISSUE TITLE
Add a media manager in Manage tab

### ISSUE THREAD

**Issue by reinboldg** [xenocrat/chyrp-lite#161]
Hello

It's possible to add a media manager in Manage tab to:

- list
- add
- remove
- rename

image, audio, video and other files in /uploads.

Best regards

**Comment by n0sheep** [comment]
I think this cannot be done, because a media is attached to his post, so if we delete the post, the media also.

I'm looking to add media in a Text post type, for example to write a tutorial with screenshots, but I can't upload media.

The Uploader post type show again the images just below the post. I don't want this behavior.

Maybe, it's possible to just list the files and don't show the images below an Uploader post type?

**Comment by n0sheep** [comment]
Maybe add a media manager in the Post view?

When I want to edit a Post, I can't edit his media.

**Comment by xenocrat** [comment]
Hello there,

Media management is a problem I haven't completely solved. However there are some tools already in Chryp Lite to help you.

In Admin > Manage > Export, you can click the ? icon beside Uploads Manifest to see a list of all uploaded files. Click on any file's name to open it in a new tab.

In Admin > Manage > Import, you can upload multiple files without creating a post, using the Bulk File Upload option. Then you can link to these files in your posts, using `img` tags (HTML) or `![description](URL)` (Markdown).

On the Write page for any feather, you can drag and drop an image file from your computer into the text boxes to upload it and add it to your post as an `img` tag.

As your wrote, renaming and deleting files from a media management page would be difficult to implement, because most uploaded files belong to a post and the post will break if the files are renamed or deleted. Adding and listing files is a simpler problem - right now it can be done, but not very conveniently. One day I hope to add UI for uploading/viewing directly on the Write pages.

I hope that helps!

**Comment by xenocrat** [comment]
The latest release includes a media management tab to view, download, and delete uploaded files. In addition the write and edit pages now have toolbars with an image upload function.
