### ISSUE TITLE
Invalid email address

### ISSUE THREAD

**Issue by roughnecks** [xenocrat/chyrp-lite#221]
Hello,
a user is trying to register but he can't.

His email provider is "e.email". It does resolve fine and has MX records set but he's receiving the error message in title (translated from Italian).
I couldn't find any particular error message in access/error.log

Thanks

**Comment by xenocrat** [comment]
Hello there,

There are client-side and sever-side sanity checks in place to prevent people trying to do various naughty things with URL and email fields; the checks are intended to be very fast but still ensure that the data entered can be safely operated on with the assumption that it's a URL/email. It's been a while since someone reported a hostname that got rejected by these checks, but your user has managed to find one. ;-)

I've modified the regular expression to allow single letter second-level domains. As far as I remember, at the time I implemented these regular expressions there was no TLD provider that allowed a single letter SLD, but I guess times haves changed.

**Comment by supersophie** [comment]
Hi,
There are many in use. Use on the .org .com was allowed again in 2005.
Off the top of my head:
u.ae  (The UAE government portal) and v.org.

Many country specific TLDs support single SLD. I don't think this is allowed on .com anymore. 

 Best, Sophie

**Comment by roughnecks** [comment]
Waiting for the user to retry, will let you know ASAP.

**Comment by roughnecks** [comment]
This is fixed, thank you!
