### ISSUE TITLE
Content of `.htaccess` is duplicated

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#23]
The `<IfModule mod_rewrite.c>` block is written twice for some reason. That said, what's the rationale behind writing and proofing it from the installation? Shipping a `htaccess` file and renaming it to `.htaccess` simplifies the process. Plus, the error message can instruct the user to rename it manually if the permissions fail.

**Comment by xenocrat** [comment]
The .htaccess is not shipped because we need to set `RewriteBase` to the install location, which might not be the web root (so we can't just assume "/").

I think the nested conditionals are confusing PHP because of the lack of closures makes the program structure ambiguous. On install the .htaccess is written because it doesn't yet exist, and because the write doesn't fail and trigger an error message, the code flows straight into the `else` append statement below. I'll add some closures to sort it out.

Thanks for the report.

**Comment by kehugter** [comment]
It covers more installation scenarios without user interaction, but clutters the installation code and makes it difficult to ship a hardened and/or cache-optimized .htaccess.

You could leave the `RewriteBase` line commented out with instructions in the file and here. For user convenience, there could be a placeholder in the shipped .htaccess (like `{{%dir}}`), which gets replaced during the installation, so that the `RewriteBase` part looks ~like

Shipped
```
# Uncomment the next line if chyrp-lite was not installed in the web root
# RewriteBase {{%dir}}
```

After installing
```
# Uncomment the next line if chyrp-lite was not installed in the web root
# RewriteBase /path/to/chyrp
```

Or just skip the commenting and simply replace the placeholder.

**Comment by xenocrat** [comment]
That's a fair point. I don't want to make the user take manual steps, but I can shift the rewrite stuff into an external file with a placeholder and write/append to .htaccess on install. That will allow for the external source to be modified for cache-optimization etc.

I need to give some thought to how this affects the repair function in upgrade.php, and if that even makes sense any more.
