### ISSUE TITLE
Apache2: Content Encoding Error

### ISSUE THREAD

**Issue by Olfried2** [xenocrat/chyrp-lite#248]
Hello,
just downloaded chyrp-lite-2024.01.01 end extracted it to my local Apache2(latest) data folder.
When I try to install chyrp-lite, I get this error message:

_Content Encoding Error
The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.
Please contact the website owners to inform them of this problem._

After checking the error.log and  access.log I cannot find any error.
The problem appears on Firefox 124.0.1 (64bit) and on opera-stable_109.0.5097.35_amd64.

Lynx says Alert!: Could not open file for decompression!
lynx: Start file could not be found or is not text/html or text/plain
      Exiting...
All my other "websites" will be processed as usual.
Any ideas what to do ?
Thanks in advance, Olfried

**Comment by xenocrat** [comment]
Hello there,

I assume the installer worked, but you are now having trouble accessing the blog after installation.

Chyrp Lite will try to automatically compress the content of web pages, using [content encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding). It's very strange for the web browser to receive an unsupported compression type, because Chyrp Lite only uses compression types the web browser specifically says it can accept. Most likely, your server or PHP installation is misconfigured in some way that is causing issues for Chyrp Lite. There are a couple of things you can do to troubleshoot the problem:

1. Check for the headers being sent when you see the error in Firefox dev tools [network details tab](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_details/index.html).
2. Edit [line 159 of _includes/common.php](https://github.com/xenocrat/chyrp-lite/blob/2024.01/includes/common.php#L159) to `if (false) {` - this will stop Chyrp Lite from trying to use any content compression.
