### ISSUE TITLE
Serving RSS feed as text instead of attachment/download

### ISSUE THREAD

**Issue by xdpirate** [xenocrat/chyrp-lite#252]
When visiting `siteurl/feed/`, users are served a randomly-named file containing an RSS feed as a download/attachment. If the user imports this into their RSS reader, the feed will not automatically update. 

Could an option be added to CL's settings where we can choose to serve the feed as text/rss/xml in-browser when clicked? I realize you can just put the url to `siteurl/feed/` into your RSS reader, but that is not evident to the user; usually when you click a feed link on a website, you're served the RSS as text in-browser and from there, the browser can let you subscribe with your preferred reader (at least some browsers do this).

**Comment by xenocrat** [comment]
Hello there,

The download as randomly-named file is something Firefox does if you don't have a feed reader app defined to handle the content type of the feed. Microsoft Edge (and probably Chrome too) will show the entire feed source as plain text. If you have a feed reader installed for Firefox (e.g. [Livemarks](https://addons.mozilla.org/en-US/firefox/addon/livemarks/)) then clicking on the "Feed" link will display the feed in a nicely structured way within the browser and allow you to subscribe. Unfortunately the default user experience with feeds in all major browsers is quite poor, as a result of browser vendors deciding to confine feeds to the dustbin of history. This is despite - or in the case of Google, perhaps because of - their usefulness to users who do not wish to capitulate to the algorithmic feeds of surveillance capitalism.

The feeds generated by Chyrp Lite are always served with the correct content type as defined in the format spec: `application/atom+xml` for Atom, `application/rss+xml` for RSS, and `application/feed+json` for JSON.

**Comment by xdpirate** [comment]
I had no idea this was a browser issue as I exclusively use Firefox. Thanks for the explanation - I tested in Chromium and it works as expected there.

**Comment by xenocrat** [comment]
No problem at all. I've used the Livemarks add-on since feed reading support was removed from Firefox, so I wasn't aware of Firefox's download behaviour until you mentioned it and I did some testing. Thanks for bringing it to my attention!
