### ISSUE TITLE
Login page for guests without `View Site` permission

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#28]
If you remove all permissions from a guests, chyrp-lite's root looks fine:

```
Access Denied
You are not allowed to view this site.
```

Nothing else is displayed. `index.php` prevents users from locking themselves out (https://github.com/xenocrat/chyrp-lite/blob/5a483b7144088a3343ebcc3e34d3be9055d4d3a9/index.php#L15), which is good. However, i see some problems:

- the allowed actions (login, et al) are displayed inside the site default theme. That means that email, tags and other information that shouldn't be public is revealed.
- `/?action=login` is easy for the admin to remember, but not for collaborators. The root should display the login form if necessary.

I think that an independent login + register page (that doesn't extend default.twig) for this case would be the best way to go. It has the positive side effect of reducing chyrp-lite's fingerprint.

If the site is public, then there's no problem in keeping the login form inside the default template.

**Comment by xenocrat** [comment]
A totally private site is quite a niche requirement. This can be handled by writing a simple module that responds to the "can_not_view_site" [trigger](https://github.com/xenocrat/chyrp-lite/wiki/Introduction-to-Triggers) and displays a custom/standalone login page including specific instructions telling the user how to acquire a login if they don't have one (i.e. a paywall). Maybe I'll put something together to show how it could be done.

If you want to use the default login form but you are worried about leaking data, you can wrap the display of those things in `{% if visitor.group.can("view_site") %}` Twig conditional.

**Comment by xenocrat** [comment]
It would be easy to raise a [Flash](https://github.com/xenocrat/chyrp-lite/wiki/Glossary-of-Terms#flash) warning and redirect to the login page instead of throwing an error in index.php. This would certainly make it easier for registered users to log in, but I need to think over the implications of this change before I implement it.

**Comment by kehugter** [comment]
> wrap the display [...] in Twig conditional

That's what I did for my live site. I still think that no `View Site` permissions shouldn't display the site at all, to be concordant with the name. Otherwise it could be renamed to something like `View Published Content`.

> paywall

Vade retro! You can also have a private site for your family or a small group of known people :)

**Comment by xenocrat** [comment]
In the end it's just two paths to the same solution. For the few admins who prefer enhanced privacy a couple of Twig conditionals do the trick. On the flip side, if an admin likes the current behaviour and I change it, they'll have to write a module just to revert it. I prefer to encourage customisations in Twig whenever possible because of the friendly syntax and reduced scope for screwing things up.
