### ISSUE TITLE
Add more options to the importers

### ISSUE THREAD

**Issue by kehugter** [xenocrat/chyrp-lite#29]
I'm working on adding more options to the importers: custom status, timestamp, tags and category. Would you like to get it as a PR when it's done? Otherwise I'll make a dedicated fork and post the link here.

**Comment by xenocrat** [comment]
Please do create a PR once you are done, I'd certainly like to take a look. I'm more likely to accept a PR if the code changes are isolated to the importers module because I prefer not to clutter other areas of the codebase with import code for third-party platforms. Either way, it will be nice to see the result of your endeavour!

**Comment by kreativmind** [comment]
Any progress on this?
