### ISSUE TITLE
Trying to install from master repo

### ISSUE THREAD

**Issue by kreativmind** [xenocrat/chyrp-lite#36]
I am getting an error on line 543 of install.php

Parse error: syntax error, unexpected ';', expecting ')' in /install.php on line 543
Line 543:  $set = array($config->set("sql", $settings);

Also, why is it so much different than the 2016-03 install.php file?
Line 543:  $config->set("sql", array());

**Comment by xenocrat** [comment]
Thanks for the report. Some test installs are next on my pre-release checklist, but you've beat me to it.

Line 543 is different because I decided, since we build the SQL settings ahead of time, we may as well write them here instead of writing an empty array and then overwriting the empty SLQ settings in a subsequent step. That change allowed me to remove config manipulation from the SQL class – that capability really doesn't belong there – and make all config changes the domain of the Config class. The other change is to build an array of all the return values and check if the array contains `false`, which indicates a failed write.
