### ISSUE TITLE
Invalid security key

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#42]
Noticed a problem with access using Chrome on Android device.
First time logging into admin panel I get the message "Access Denied Invalid security key".
On the second time it finally lets me in, but still the Invalid security key message appears when trying to apply any changes in admin panel: settings, themes, writing a post, etc.
Other browsers seem to handle everything just fine. But still curious what might be the case and how it can be solved?

**Comment by xenocrat** [comment]
That's an odd problem. The "security key" is Chyrp Lite's CSRF token which is inserted into pages that allow privileged actions. The token is a hash of a secret stored on the server combined with the IP address of the client that requested the page, so for it to be invalid one of three things is happening:

1. Your IP address is changing between the time you loaded the page and applied the changes – but I would expect this to also affect other browsers on the device.
2. Chrome is changing or removing the value of the token in the pages so that when you apply the changes, the token is rejected.
3. The page contains an invalid token when loaded because something between you and the server is caching the pages despite being told not to do so by Chyrp Lite – perhaps an overly aggressive proxy.

**Comment by Dextrolain** [comment]
Thank you for the tips, the problem was in Chrome's "Data saver" function which made all traffic go through google servers. Turned it off and everything works perfectly fine.
