### ISSUE TITLE
Theme caching

### ISSUE THREAD

**Issue by dahliadahlia** [xenocrat/chyrp-lite#46]
Hello again!

I'm attempting to create a theme and the design keeps caching. I think it's a twig caching issue but I'm not a hundred percent sure.

For example, I removed links in the default.twig menu area and they still persist, among other small changes. Like adding a line of text or adding random inline CSS to make sure things are actually updating (these "test" additions don't show up).

I've cleared my browser cache (Chrome), and disabled caching (as far as I can tell) from my local AMPPS installation.

(also I'm very sorry for constantly showing up!)

**Comment by dahliadahlia** [comment]
I think it's my test server, to be quite honest. Sorry for the false alarm.

**Comment by xenocrat** [comment]
Don't worry about asking questions, I am happy to help whenever I can.

I think Twig template caching is your problem. There are two solutions to this: one option is to enable [debug mode](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes) which will cause Twig to cache much less aggressively so that updated templates will be reloaded (I develop all themes in this mode, but be aware that debug mode has wider implications and is not a good idea for a production environment); the other option is to disable Twig caching by find this line in _common.php_:

    define('CACHE_TWIG', is_dir(CACHES_DIR.DIR."twig") and is_writable(CACHES_DIR.DIR."twig"));

And changing it to this:

    define('CACHE_TWIG', false);

**Comment by dahliadahlia** [comment]
Funny enough my husband just helped me with the exact same solution, he changed the twig caching to "false".

I was at my wit's end, to be quite honest. I'm happy this is online for people to see.
