### ISSUE TITLE
Numeric Tags causing Offset Error in Tag-Class

### ISSUE THREAD

**Issue by hasslerf** [xenocrat/chyrp-lite#5]
When adding a numeric Tag like "4212", our postal code, I get:

    Notice: Undefined offset: 4212 in /home/.sites/664/site489/web/chyrp-lite/modules/tags/tags.php on line 614
    Notice: Undefined offset: 4212 in /home/.sites/664/site489/web/chyrp-lite/modules/tags/tags.php on line 615

I removed the tag in the Database where there are no Quotes around the newly added tag which probably causes the error:

    neumarkt: "neumarkt"
    4212: 4212

First line is a working tag, second one does not work.

**Comment by xenocrat** [comment]
Thanks for the report. I've been doing a major overhaul of the tags module ahead of the next release, and I'm pleased to tell you this bug is no longer present in the development branch. However your report did help me to discover another bug with numeric tags that made it impossible to edit or delete them, which I've fixed [here](https://github.com/xenocrat/chyrp-lite/commit/99d0a7eb891c5d58f1c2c709d5779086a7d1d915).

I hope to release the next version of Chyrp Lite featuring these fixes very soon.

**Comment by xenocrat** [comment]
Chyrp Lite v2015.05.25 was [released](https://github.com/xenocrat/chyrp-lite/releases/tag/v2015.05.25) today. If you discover any new problems, please do let me know and I will try my best to fix them!

**Comment by hasslerf** [comment]
Thanks a lot!
