### ISSUE TITLE
chyrp not working on IIS

### ISSUE THREAD

**Issue by starshine531** [xenocrat/chyrp-lite#53]
My server is running IIS (not my choice). I ran the install script just fine, but the index.php page just shows a blank page and there is no error message. 

I'm guessing it's because of the htaccess file not being compatible with IIS. Is there a work around for this?
Or are there larger issues with trying to use this on a windows machine?

**Comment by xenocrat** [comment]
Chyrp Lite is completely untested on IIS but in theory it should be compatible. Your lack of .htaccess support means you won't be able to use clean URLs, but otherwise things would be expected to work.

If you can switch your installation to debug mode using [these instructions](https://github.com/xenocrat/chyrp-lite/wiki/Debug-and-Tester-Modes) and let me know what you see in _error_log.txt_ then we can try to resolve the problem.

**Comment by xenocrat** [comment]
Just had a thought: perhaps your IIS server does not have _index.php_ in the list of [default documents](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/defaultdocument/). What happens if you visit _yoursite.com/installdir/**index.php?action=index**_ with the document name and action set explicitly?

**Comment by starshine531** [comment]
Sorry for slow reply. I had other projects that had to get done.
Here's the error message:
PHP Parse error:  syntax error, unexpected '[' in C:\inetpub\wwwroot\blog\chyrp\includes\controller\Admin.php on line 1614
that line reads:
foreach (load_info($folder.DIR.$name.DIR."info.php")["notifications"] as $message)

I'm using php 5.3.28. Is that the problem?

**Comment by roywikan** [comment]
Probably, one of the feather or themes info.php file contains a [ character.

Try to disable modules, feather or themes one by one, or download a new zip from github and try to do fresh install. 

I installed chyrp in linux and android smartphone without problems.

May it helps.

**Comment by roywikan** [comment]
Just to add information :
I installed chyrp lite successfully in :

Linux with nginx and php 5.6

Android smartphone using php 5.5 built-in webserver.

Fyi

**Comment by xenocrat** [comment]
Thanks for getting back to me with the error message. The cause of the problem is that I'm using syntax that requires PHP 5.4.0 or greater on lines [1614](https://github.com/xenocrat/chyrp-lite/blob/a94624e580ff910b383997ed186ffa956ae65ea8/includes/controller/Admin.php#L1614),  [1682](https://github.com/xenocrat/chyrp-lite/blob/a94624e580ff910b383997ed186ffa956ae65ea8/includes/controller/Admin.php#L1682), and [1980](https://github.com/xenocrat/chyrp-lite/blob/a94624e580ff910b383997ed186ffa956ae65ea8/includes/controller/Admin.php#L1980). Sorry about this, the stated minimum requirement is indeed 5.3.2 but the codebase is not regularly tested with versions of PHP earlier than 5.4.0 and so this mistake has managed to make it to release.

I can tell you how to make a few small modifications to _AdminController.php_ to get it working if you are interested to know, but I'm afraid I won't be fixing this problem because I have already planned for the next release of Chyrp Lite to require PHP 5.4.0 to avoid repeating these kinds of problems in future.

I hope that all makes sense. I'm very sorry that the stated minimum requirements proved to be incorrect. Thank you again for taking the time to investigate and reply.

**Comment by starshine531** [comment]
Roywikan, I don't think chyrp\includes\controller\Admin.php is a part of a feather or theme. It looks like it's a core file. I'm using IIS and PHP 5.3.28.

**Comment by starshine531** [comment]
xenocrat, thanks for the reply. I'll see if we can get a newer version of PHP on our server, but that's not my call to make. If not, I'll have to look into some other blog software.
