### ISSUE TITLE
 I can not log in and I can not register a new user.

### ISSUE THREAD

**Issue by eArabic** [xenocrat/chyrp-lite#56]
Hello
Thank you very much for this wonderful script.
I have installed it but I can not log in and I can not register a new user.
I tried to install it more than once but without interest although the data is 100% correct but I can not access the control panel.

![1](https://user-images.githubusercontent.com/24383546/33923714-bea419c2-dfe3-11e7-960d-e39f054b9d6e.png)

![2](https://user-images.githubusercontent.com/24383546/33923715-bec6f10e-dfe3-11e7-935b-b246950d1e2e.png)

The error is:
Invalid authentication token.
Please consider setting a stronger password for your account.

**Comment by eArabic** [comment]
I registered with a very strong password but the error is still persistent I can not register and log on to the control panel.

![3](https://user-images.githubusercontent.com/24383546/33924148-c434cac4-dfe5-11e7-9bc0-55a7444ed8dd.png)

**Comment by xenocrat** [comment]
The "authentication token" is Chyrp Lite's CSRF token which is inserted into pages that allow privileged actions. The token is a hash of a secret stored on the server combined with the IP address of the client that requested the page, so for it to be invalid one of three things is happening:

1. Your IP address is changing between the time you loaded the page and applied the changes.
2. Your web browser is changing or removing the value of the token in the pages so that when you apply the changes, the token is rejected.
3. The page contains an invalid token when loaded because something between you and the server is caching the pages despite being told not to do so by Chyrp Lite.

The authentication token might be a problem if you use a proxy or data-saver. For this reason it will be reimplemented in the upcoming release of Chyrp Lite using a different method. You can try making changes to your network connection (disable proxies and data-savers if possible) or you could try upgrading using a download from the master branch (use the “clone or download” button to do this).
