### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#60]
Hi. I'm trying to implement a dropdown menu for the "Pages" block in the navigation.
Not sure if I found adequate solution, but everything works...except one detail about `.page.depth2`
Page name link and it's child item links seem to have same source in here `<a role="menuitem" href="{{ item.url() }}">{{ item.title }}</a>` in sidebar.twig
I'm trying to find a way to make Page name link inactive (keeping only the title), but keep child item links active, so supposedly I need to divide the link source somehow.
Could you give any hints on this matter please?
Or maybe there is an easier/neater way that I just can't notice?

Here is an example of the code:

```
<script type="text/javascript">
	$(document).ready(function () {  
	$('ul.navigation').click(function () {  
	$('li.page.depth2').slideToggle('medium');  
});  
});  
</script>
-----------------
{% if theme.pages_list() is not empty %}
<ul role="menu" class="navigation" aria-labelledby="label_my_pages">
{% for item in theme.pages_list(2) %}
<li role="presentation" class="page depth{{ item.depth }}">
<a role="menuitem" href="{{ item.url() }}">{{ item.title }}</a>
</li>
{% endfor %}
</ul>
{% endif %}
-----------------
ul.navigation li.page.depth2 { display: none }
```

**Comment by xenocrat** [comment]
The items in the pages list have a `children` attribute that will be `true` or `false`. If you want to disable the link for any pages that have children, you can test this.

The depth class name is there to allow visual indentation (and I need to fix this because page depth might be greater than 4). To make an interactive pages list that works in all situations, it would be better to target a parent ID. Something like this would work:

    <script type="text/javascript">
        $(document).ready(function () {
            $("ul.navigation li.page[data-children]").click(function (e) {
            	e.preventDefault();
                var id = $(this).attr("data-pageID");

                $("ul.navigation li.page[data-parentID='" + id + "']").each(function() {
                    $(this).slideToggle("medium");
                });
            });
        });
    </script>

With this Twig code:

    {% set my_root_page = 0 %}
    {% for item in theme.pages_list(my_root_page) %}
    <li role="presentation" class="page"
    data-pageID="{{ item.id}}"
    data-parentID="{{ item.parent_id }}"
    {% if item.children %} data-children{% endif %}
    {% if item.parent_id != my_root_page %} style="display: none;"{% endif %}>
    <a role="menuitem" href="{{ item.url() }}">{{ item.title }}</a>
    </li>
    {% endfor %}


You'll need to think about if and how you allow visitors to visit a page that has children – right now clicking on those pages just shows/hides their children.

**Comment by Dextrolain** [comment]
That works perfectly. I'll think about the last part.
Thanks for your help again.
