### ISSUE TITLE
Invalid authentication token

### ISSUE THREAD

**Issue by Dextrolain** [xenocrat/chyrp-lite#61]
Hi, I've had a similar trouble earlier, but it's different this time, I guess. 
Encountered this problem trying to log in to my site after the upgrade to the latest release of Chyrp. 
Fresh install of Chyrp with my existing database almost doesn't have this problem.
"Almost" because even in completely fresh install without the old database this problem occures when you click "update" button in Cascade settings. In all other aspects fresh install works perfectly fine, as far as tested it.
Could there be some incompatibility with the previous CSRF token method?

**Comment by xenocrat** [comment]
Hello there. I'm not sure from your description if your problem is just with the Cascade settings page or is more widespread.

I've just checked cascade_settings.twig and discovered that I did not update the authentication method when I did all other admin pages. You can fix the problem by using the patched file linked above.

If you are having more widespread problems after an upgrade, make sure you have deleted the contents of _includes/caches/twig/_ (and if you are using the Cacher module, also delete the contents of _includes/caches/pages/_).

**Comment by Dextrolain** [comment]
Thank you for the fix. The cascade settings was the only problem that I noticed on a fresh install of Chyrp.
But the main problem is when I upgrade existing (Cape release) site to the latest release I get the same token problem when I try to login to existing user accounts.
Deleting the cache didn't help.

**Comment by xenocrat** [comment]
There’s nothing stored permanently in database or config files that affects the CSRF tokens, so if everything works ok for a new install it should also work for an upgrade. Only things that would make it fail are caching or a page sending an old-style token to a responder expecting a new-style token.

What blog theme are you using, and did you upgrade it along with the rest of the Chyrp Lite installation? Find the file _themes/yourtheme/forms/user/login.twig_ and make sure it contains a line that look like this:

    <input type="hidden" name="hash" value="{{ authenticate() }}" id="hash">

If there is some other value, such as “ip | token” then that’s the cause of your problem.

**Comment by Dextrolain** [comment]
That's where my problem was. I have own separate theme, so it wasn't updated.
Now everything works properly.
Thanks a lot.

**Comment by xenocrat** [comment]
I'm glad that fixed it. Sorry for the disruption. Now that token generation is properly abstracted into a helper function, no more changes should be needed on the theme side in future.
