### ISSUE TITLE
Minify css for the highlight plugin

### ISSUE THREAD

**Issue by meskarune** [xenocrat/chyrp-lite#75]
I guess what it says in the title. Have the css for the highlight.js module minified by default.

**Comment by xenocrat** [comment]
I will respond to the PR separately, but I will also leave a comment here to address the issue in more general terms.

Overall I have decided against minifying CSS and JavaScript payloads because it's important to me that users feel encouraged to delve into and understand every aspect of their Chyrp Lite installation. It also makes life easier for me, which I consider a top priority. =) This does result in higher initial load times for visitors but after the first download the static files will be cached by the browser. Dynamically generated files are usually compressed.

The exceptions to this rule are third-party components bundled with Chyrp Lite without modification. For example, jQuery. It makes sense to minify this particular file, but in most cases I prefer the simplicity of readable code even if it sacrifices absolute performance.

**Comment by meskarune** [comment]
I can understand your point. Would it be possible to have a regular css file and minified one with the minified being used? Or maybe chyrp-lite can minify static files when it caches? Then people can update the regular file as they will and/or run a minification command. Many ISP's limit bandwidth and charge overages and people with certain phone plans have limited bandwidth and I think it is worth serving a site with the lowest possible bandwidth usage.

I would be willing to go through stock themes/modules to make minified versions of js/css. Obviously working on one thing at a time and making small PRs that are easy to check.

Of course ease of maintenance is important though, and minified stuff is not the most human readable, and minifying things adds an additional step.

**Comment by xenocrat** [comment]
It's good reasoning, and I am aware of the bandwidth limitations on users and hosts alike. I run my Chyrp Lite installation on a bandwidth- and CPU-limited shared host, and I think this helps me to keep my "lightweight" promise in mind.

Reading your suggestion, I can think of a few different ways to achieve the goals, but they all increase the complexity of the platform in ways that I think cancel out the gains. That's not to say that your suggestion is bad, but rather that I am a lazy idiot. And I like to characterize my lazy idiocy as an aversion to complexity. When I think of the best way to make some gains with the least amount of effort on my part I think of this:

Chyrp Lite's JavaScript is dynamically generated, or static and minified. So I think we can disregard the JS as mostly a solved problem. The HTML is served dynamically, without indentation (check the twigs) and with compression wherever available.

However most of the CSS for admin and themes is static and looks like this:

    i.am.a.rule {                         color: red;
                                          background-color: transparent }

I like the readability of that. But this would also be very readable and it would save an average of 44 bytes per line per CSS file without compression or minification:

    i.am.a.rule {
        color: red;
        background-color: transparent;
    }

Making the change is boring work but it will result in a real-world gain with zero cost in terms of complexity. It's not the same gain in terms of absolute performance as what you suggested, but it's still a decent gain and it's idiot-proof. I like PRs that are idiot-proof.

**Comment by xenocrat** [comment]
I just [tested my idea](https://github.com/xenocrat/chyrp-lite/commit/5409c6c279b3bb7068a3b5cd3de3cf12d5e52406) on the admin console's CSS. Payload is down from 43KB to 23KB.

**Comment by meskarune** [comment]
Oh wow, nice :smile:

**Comment by xenocrat** [comment]
I've done the same optimization on all themes, resulting in similar gains. I think that's a nice outcome, so I'm going to close this issue.
