### ISSUE TITLE
Error when installing 2015.06

### ISSUE THREAD

**Issue by mtech** [xenocrat/chyrp-lite#8]
I get the following messages when installing.

Notice: Only variable references should be returned by reference in /includes/class/Config.php on line 135

Notice: Only variable references should be returned by reference in /includes/class/SQL.php on line 465

Notice: Only variable references should be returned by reference in /includes/class/SQL.php on line 468

**Comment by mtech** [comment]
Take note that it does install and seem to be running perfectly fine. The messages show up above the box with the info to delete the install.php file and Take me to my site link.

**Comment by xenocrat** [comment]
Thanks for the report. These notices have been fixed in the development branch for Chyrp Lite 2015.07, which I plan to release in November. In the meantime, they won't cause any harm – it's just PHP complaining that something is not strictly correct. There's quite a few instances of old code in the core that trigger these notices on more recent versions of PHP.

I've been doing a lot of work to ensure 2015.07 will run in PHP's strict mode without error, and trying to ensure the codebase is compatible with the upcoming PHP 7, so hopefully you won't see any more of these messages soon!

**Comment by mtech** [comment]
No problem. Glad to see the project is still alive. I noticed chyrp.net is down. I am guessing he decided to stop active dev on it.

**Comment by xenocrat** [comment]
I noticed the same. I don't know what the situation is with @chyrp but I can tell you that I plan to continue maintaining this project. I think the codebase is finally in good shape to face the future, so I hope the task will not be too overwhelming.

I do plan to transition from the disruptive changes of the last year to a more leisurely pattern of stable maintenance releases.

**Comment by mtech** [comment]
That sounds great to hear. I am hoping to work on some new themes as soon as I finish a few projects I am working on for clients.
