### ISSUE TITLE
Disable cookies unless user logs in

### ISSUE THREAD

**Issue by jocap** [xenocrat/chyrp-lite#87]
Hi,

I'm trying out Chyrp and I really like it so far. I'm just wondering if it would be possible to disable cookies for all visitors, unless they log in. I'm under the impression that Chyrp currently sets cookies even if the visitor never logs in. Is this correct?

**Comment by xenocrat** [comment]
Hello there. Your statement is correct. Chyrp Lite only ever sets one cookie containing a PHP session ID, but it does so for all visitors. There is no way to disable this cookie, because the session is used on the server side to provide functionality even to logged out visitors e.g. keeping track of the comments and likes created by anonymous visitors.

Is there something specific that worries you about this behaviour?
