### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by nodefive** [xenocrat/chyrp-lite#90]
Just a constructive critique. Photos can only upload one picture per article. That without an actual media uploader breaks the whole easy of use of the system as one needs to upload them manually over FTP or some other means. 

A plugin to upload media files (or any file) would be awesome. Aside from this issue the chyrp-lite system rocks. Light, fast, simple to admin it and simple for readers, in other words: awesome!

**Comment by xenocrat** [comment]
Hello there. Thanks for your kind words and for the feature request. I will look at the possibility of adding an upload management page to show a list of uploaded files and offer bulk upload of new files.

**Comment by xenocrat** [comment]
I've added some features for users who wish to upload files and link to them in the body of blog posts, instead of using Feathers to upload files one at a time. The next release will add the ability to upload files in bulk on the on the Manage > Import page, and to view a manifest of the uploaded files on the Manage > Export page.

**Comment by nodefive** [comment]
Awesome, thanks mate!
