### ISSUE TITLE
 Comments module out of order

### ISSUE THREAD

**Issue by Torsten-K** [xenocrat/chyrp-lite#91]
I've enabled the Comments module, and there's in deed a link under the blog posts, so it should be possible to comment, but that doesn't work. There’s simply no text box opened where you can write your comments.

Apache 2.4 with PHP 7.2.

**Comment by xenocrat** [comment]
Hello there. Each group of users needs to be given permission to comment. You can do this by going to Admin > Manage > Groups, and giving the desired groups permission to "Add Comments". There's also several other permissions related to comments that you might want to give to users and/or administrators to help them manage comments.

These permissions are not set by default because it's your decision who gets to comment on your blog. I hope that helps!

**Comment by Torsten-K** [comment]
Thank you for your help. I didn't know I had to make the adjustments you told me. Now the comment system works all right. Great! I love Chyrp Lite more and more. Thanks again!
