### ISSUE TITLE
Configuration for Caddy?

### ISSUE THREAD

**Issue by hypervtechnics** [xenocrat/chyrp-lite#93]
I just found this one for another PHP application: https://github.com/caddyserver/examples/tree/master/cmsmadesimple

**Comment by xenocrat** [comment]
Hello there. I think something like the linked readme is outside the scope of this project. A web server running PHP with a database adaptor is a prerequisite for installing Chyrp Lite. These software packages have their own support forums and guides.

What I think is within scope is creating a caddyfile configurator to go alongside the htaccess configurator, so that Chyrp Lite could offer clean URL support when running on Caddy. I've started work on this in the develop branch.
