### ISSUE TITLE
SimpleMDE removed

### ISSUE THREAD

**Issue by Maffsie** [xenocrat/chyrp-lite#95]
Hi,

I saw that the 2014.9 release removes SimpleMDE - I was using this for friendlier Markdown editing. I can see the commit that removed it, but can find no indications for why it would be removed. Why was this removed, and is there plans to replace it?

**Comment by xenocrat** [comment]
Hello there.

I removed SimpleMDE because the project has been inactive for several years and [appears to have been abandoned](https://github.com/sparksuite/simplemde-markdown-editor/issues/740). There are some active forks of the project but I decided I don't want to spend my limited development time solving problems of this type, so I chose to remove the module from Chyrp Lite. I'm always eager to reduce the number of dependencies I have to track, and reduce the likelihood that I will have to triage other people's bugs instead of the ample number I am able to create with my own code.

You can extract the SimpleMDE module's folder from the [2019.03](https://github.com/xenocrat/chyrp-lite/releases/tag/v2019.03) release of Chyrp Lite and continue to use it with 2019.04 and beyond. No breaking changes have been made, and none are planned at this time.

I hope that helps to explain things.

**Comment by Maffsie** [comment]
Hi @xenocrat,

Thanks for the explanation - I can certainly understand wanting to reduce external dependencies (I wish that desire were more prevalent). For now I'll pull in the SimpleMDE module from the previous release as advised, and start figuring out the best way to move on from it.

Thanks!
